name: lz4 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-latest:
    name: Build on Ubuntu x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: make test

  ubuntu-latest-aarch64:
    name: Build on ubuntu-latest aarch64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu-latest
        githubToken: ${{ github.token }}
        # Set an output parameter `uname` for use in subsequent steps
        name: make test
        run: make test

  macos-latest:
    name: Build on macos
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: make test
